service: tick-webhook
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1 

functions:
  hello:
    handler: handler.tick
    events:
      - httpApi:
          path: /
          method: post

resources:
  Resources:
    devTable:
      Type: AWS::DynamoDB::Table 
      Properties:
        TableName: tick-dev
        BillingMode: PAY_PER_REQUEST 
        AttributeDefinitions:
          - AttributeName: id 
            AttributeType: S 
        KeySchema:  
          - AttributeName: id 
            KeyType: HASH
    prodTable:
      Type: AWS::DynamoDB::Table 
      Properties:
        TableName: tick-prod
        BillingMode: PAY_PER_REQUEST 
        AttributeDefinitions:
          - AttributeName: id 
            AttributeType: S 
        KeySchema:  
          - AttributeName: id 
            KeyType: HASH